import Head from 'next/head';
import { useRouter } from 'next/router';
import { GetStaticProps, InferGetStaticPropsType } from 'next';
import Image from 'next/image';
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
import { useTranslation } from 'next-i18next';

import styles from '@/styles/Home.module.css';
import { trpc } from '../utils/trpc';
import { getStripe } from '@/utils/stripe';
import localFont from '@next/font/local';
import Logo from '@/components/Logo';
import Demo from '@/components/Demo';
import Steps from '@/components/Steps';

const shibuya = localFont({ src: '../fonts/go3.ttf' });

type Props = InferGetStaticPropsType<typeof getStaticProps>;

export default function Home(_props: Props) {
  const { t } = useTranslation('home');
  const { locale, locales } = useRouter();
  console.log({ locale, locales });
  const purchase = trpc.payments.purchase.useMutation();

  const handlePurchase = async () => {
    const stripe = await getStripe();
    const { id } = await purchase.mutateAsync();
    stripe?.redirectToCheckout({ sessionId: id });
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Logo />
        <div className="hero min-h-screen" style={{ backgroundImage: `url("/night-bg.gif")` }}>
          <div className="hero-overlay bg-black bg-opacity-60"></div>
          {/* <img src="/japan.png" className="max-w-sm"></img> */}
          <div className="hero-content text-center text-white flex flex-col">
            <div className="max-w-lg">
              <h1 className={`flex flex-col mb-6 text-6xl font-semibold ${shibuya.className}`}>
                <span>{t('title.line-1')}</span>
                <span
                  className={`${shibuya.className} tracking-wider text-7xl text-transparent bg-clip-text bg-gradient-to-b from-purple-400 to-pink-600 mt-4`}
                >
                  {t('title.line-2')}
                </span>
                <span>{t('title.line-3')}</span>
              </h1>
              <div className="my-5">
                <p className="text-lg my-2">🔒 {t('features.payment')}</p>
                <p className="text-lg my-2">✨ {t('features.quality')}</p>
                <p className="text-lg my-2">🌀 {t('features.amount')}</p>
                <p className="text-lg my-2">🎆 {t('features.description')}</p>
              </div>
            </div>
            <div className="flex items-center mt-24">
              <p className="text-xs opacity-50 mr-6">{t('seen-on')}</p>
              <img
                loading="lazy"
                className="h-6 mr-6 filter-to-white"
                src="https://avatarai.me/assets/techcrunch.png?1670866305"
              />
              <img
                loading="lazy"
                className="h-6 mr-6 filter-to-white"
                src="https://avatarai.me/assets/stability-ai.png?1671498407"
              />
              <img
                loading="lazy"
                className="h-6 mr-6 filter-to-white"
                src="https://avatarai.me/assets/fstoppers.png?1670867107"
              />
              <img
                loading="lazy"
                className="h-6 mr-6 filter-to-white"
                src="https://avatarai.me/assets/tiktok.png?1670866305"
              />
              <img
                loading="lazy"
                className="h-6 mr-6 mt-1 filter-to-white"
                src="https://avatarai.me/assets/instagram.png?1670870083"
              />
            </div>
          </div>
          <div className="fixed bottom-0 w-full text-center bg-brand border-t border-slate-500 p-6 z-50">
            <button onClick={handlePurchase} className="cta btn btn-primary glow w-80">
              {t('cta-start')} - 9.99€
            </button>
          </div>
        </div>
        <section>
          <div className="w-[60%] mx-auto text-center p-12">
            <h2 className="text-3xl font-bold mb-6">🌀 Get 5 different anime styles</h2>
            <p>
              After payment you can select up to 15 styles you want from the ones below. For each
              style we'll generate 8 avatars, for a total of 120+ avatars. With AI, results can
              vary, so we generate a lot of avatars so you can pick the best ones! Transform
              yourself (or your dog, cat, or you and your bf/gf as a couple) into desert punk
              warriors, a zombie at Halloween, an Instagram model in the jungle, the main character
              in a video game to a fashion model. It's up to you to decide who you want to become!
              Your AI avatars will look just like you but in the styles you select.
            </p>
            <Demo />
          </div>
        </section>
        <hr className="w-full border-slate-500" />

        <Steps />

        <hr className="w-full border-slate-500" />
        <section className="w-[60%] mx-auto text-center p-12">
          <h2 className="text-3xl font-bold mb-6">❓ Frequently Asked Questions</h2>
          <div>
            <h3 className="text-2xl font-semibold mb-4">What type of photos should I upload?</h3>
            <p>
              We recommend 10 close ups of your face, 3 photos of your side profile, 5 photos from
              your chest and up and 3 full body photos. The more different your photos are from each
              other the better! Make sure there's no other people or animals in your photos than the
              main subject (you, or your dog, or cat, or your bf/gf if you selected couple). Photos
              with a variety of facial expressions, locations, backgrouns and perspecitves are
              better. Don't just look into the camera, also look away! High quality photos work
              better. If you like to wear makeup, make sure it's minimal in your photos, or it may
              be exaggerated in the avatars. Please don't upload nudes. Swimwear and underwear is
              fine
            </p>
          </div>
          <h3 className="text-2xl font-semibold mb-4">
            What file formats of photos do you accept?
          </h3>
          <p>
            Right now we support JPG, PNG, WebP, HEIC, JFIF, TIFF and RAW. We don't support AVIF or
            GIF!
          </p>
          <h3 className="text-2xl font-semibold mb-4">
            How long will it take to receive my avatars?
          </h3>
          <p>
            Right now it'll take about 37 minutes (based on current processing times) to generate
            your avatars.
          </p>
          <h3 className="text-2xl font-semibold mb-4">What will you do with my photos?</h3>
          <p>
            Great question. We only use them to train the AI model, render your avatars and then
            delete both the input photos and the AI model from our servers and the GPU API's servers
            (where it's processed) within 24 hours. Beware of other apps that generate profile
            photos and avatars as most store your data forever to mine it which means they can
            generate any image (like deepfakes) with your face in it forever. Some are even
            affiliated with foreign governments with might get your data!
          </p>
        </section>
      </main>
    </>
  );
}

export const getStaticProps: GetStaticProps = async ({ locale = 'en' }) => {
  return {
    props: {
      ...(await serverSideTranslations(locale, ['home'])),
    },
  };
};
